# 블로그 제목과 설명
title: "omm0716's DevLog"
description: "프로그래밍 및 데이터 분석 기록"

# 테마 불러오기 (가장 중요한 부분!)
remote_theme: "manid2/lone-wolf-theme"

# 부가 기능(플러그인) 연결
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# 내 블로그 주소 (본인 아이디로 꼭 바꾸세요)
url: "https://omm0716.github.io"
baseurl: ""
# _config.yml에 추가 또는 수정
author:
  name: "omm0716"
  location: "South Korea"
  email: "omm1532@gmail.com"

# SNS 링크 (테마 설정에 따라 다를 수 있음)
twitter_username: "omm1532"
github_username:  "omm0716"
logo: "https://cdn-icons-png.flaticon.com/512/6062/6062646.png"
